### PR TITLE
Compatibility for FileSystemWatchers under OSX

### PR DESCRIPTION
**Pull request by xPumaa**
tested with Reve#6583

### CODE REVIEW

**Comment by rootdarkarchon** [comment]
will this take as it's not running under osx but under wine as a windows application?

**Comment by xPumaa** [comment]
"xiv for mac" runs with wine

**Comment by rootdarkarchon** [comment]
yes that's exactly my point, how does `IsOSPlatform` handle wine? does it detect itself as OSX?

**Comment by xPumaa** [comment]
should be so. reve tested this build and it worked

**Pull request merged**
