### PR TITLE
Allow Resizing of Settings menu.

### PR DESCRIPTION
**Pull request by LunixWasTaken**
Fix for [https://discord.com/channels/984437330972655656/993940680206450818/1004947016633303060](https://discord.com/channels/984437330972655656/993940680206450818/1004947016633303060)

### CODE REVIEW

**Comment by xPumaa** [comment]
but why tho?

**Comment by xPumaa** [comment]
Okay, but that doesn't really solve the problem.
The same can and will happen in the intro

**Comment by LunixWasTaken** [comment]
> That doesn't really solve the problem. The same can and will happen in the intro
> but why tho?

If you would have actually clicked the link and read the context i was referring to, it was the case of a user having a too high font size for the save button to be displayed. this is simply a fix to not have this happen in the future.

**Comment by rootdarkarchon** [comment]
Yeah i can see that, but i don't like changing the size of the window. Pumaa has already added a PR that dynamically calculates the size of the input box based on text size which i think is better for this usecase. Thank you for your PR and thoughts though.

**Pull request closed without merging**
