### PR TITLE
Support downloading from http

### PR DESCRIPTION
**Pull request by thattuys**
Add http support to downloads(ws:// connections and uploads already work, this is just fixing the downloads)

### CODE REVIEW

**Comment by NCC-Lykos** [comment]
But....why?

**Comment by thattuys** [comment]
because it already supports running your own server without SSL, this is just fixing it, I asked Dark and was told to open a PR, the other alternative would be to add sanity checking on the input and on the server side to fully disallow unencrypted setups.

**Comment by NCC-Lykos** [comment]
> 

But why would you ever run your own server without SSL when there are things like certbot and letsencrypt? I'd say disallow unencrypted.

**Comment by thattuys** [comment]
🤔 you can get a valid ssl cert for localhost?

**Comment by Deckerz** [comment]
Create your own SSL cert and add it to your local trusted sources. .NET Core does this already it's a commonly accepted solution.

**Comment by NCC-Lykos** [comment]
> 🤔 you can get a valid ssl cert for localhost?

Why are you trying to run it as localhost? I'd say your PR needs more clarity then and to only allow non SSL on localhost and connections from localhost.... otherwise require it.

**Comment by thattuys** [comment]
Listen, if you don't want to read the conversation in discord, I asked if it was intentional, and then told to open a PR to change it. Honestly, I am +1 to disallow unencrypted but this is what I was told to open the PR for

**Comment by rootdarkarchon** [comment]
yes it's correct. I don't mind this, but I don't like the implementation. it will replace all 'wss' which could also be in the domain with 'ws' which will be problematic.

**Comment by rootdarkarchon** [comment]
or rather, all ws with http, which is also problematic. it should only replace the first occurence.

**Pull request merged**
